<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="css/bootstrap.min.css">
</head>
<?php
$title = 'Top 10 Musica POP en Inglés';
$this->headTitle($title);
?>
<font face="Times" color="white">
<h1 style="font-size:50px" align="center"><?= $this->escapeHtml($title) ?></h1>
</font>
<body>
<div class="jumbotron">
<table class="table">
<tr>
    <th>Titulo</th>
    <th>Artista</th>
	<th>Pa&iacute;s</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
    <tr>
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
		<td><?= $this->escapeHtml($album->pais) ?></td>
        <td align="left">
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Editar</a>
            <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Borrar</a>			
        </td>
    </tr>
<?php endforeach; ?>
</table>
<p align="center" style="font-size:30px">
    <a  href="<?= $this->url('album', ['action' => 'add']) ?>">Agregar Nuevo Album</a>	
</p>
</div>

<table class="table">
<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<img src="img/banda.png" width="300px" alt="">
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<img ide="img-album" src="img/imaginedragons.jpg" width="300px" alt="">
					<audio ide="player" controls=""></audio>
				</div>
				<div class="col-md-6">
					<button class="btn btn-success" ide="shuffle"><i class="fa fa-random"></i></button>
					<ul class="list-group" ide="playlist"></ul>
				</div>
			</div>
		<script src="js/jquery-3.1.0.min.js"></script>
		<script src="js/tether.min.js"></script>		
		<script src="js/bootstrap.min.js"></script>
		<script src="https://use.fontawesome.com/dccd84ec6f.js"></script>
		<script src="js/app.js"></script>
	</div>
</table>
</BODY>
